## A tf.Tensor has the following properties:
    a data type (float32, int32, or string, for example)
    a shape

0	--- Scalar (magnitude only)

1	--- Vector (magnitude and direction)

2	--- Matrix (table of numbers)

3	--- 3-Tensor (cube of numbers)

n	--- n-Tensor (you get the idea)


## Rank 0

In [1]:
import os
import tensorflow as tf
os.environ["CUDA_VISIBLE_DEVICES"] = ""
sess = tf.InteractiveSession()

In [2]:
nammal = tf.Variable(initial_value='Elephant', dtype=tf.string, name='elephant')
print(nammal)

<tf.Variable 'elephant:0' shape=() dtype=string_ref>


In [3]:
ignition = tf.Variable(initial_value=245, dtype=tf.int16)
print(ignition)

<tf.Variable 'Variable:0' shape=() dtype=int16_ref>


In [4]:
floating = tf.Variable(initial_value=3.1415926, dtype=tf.float64)
print(floating)

<tf.Variable 'Variable_1:0' shape=() dtype=float64_ref>


In [5]:
its_complicated = tf.Variable((12.3, -4.85), tf.complex64)
print(its_complicated)

<tf.Variable 'Variable_2:0' shape=(2,) dtype=float32_ref>


## Rank 1

In [6]:
mystr = tf.Variable(initial_value=["hello"], dtype=tf.string)
print(mystr)

<tf.Variable 'Variable_3:0' shape=(1,) dtype=string_ref>


In [7]:
mystr2 = tf.Variable(initial_value=["hello","world"], dtype=tf.string)
print(mystr2)

<tf.Variable 'Variable_4:0' shape=(2,) dtype=string_ref>


In [8]:
mystr3 = tf.Variable(initial_value=[["hello", "TF"],["world", "2018"]], dtype=tf.string)
print(mystr3)

<tf.Variable 'Variable_5:0' shape=(2, 2) dtype=string_ref>


In [9]:
cool_numbers = tf.Variable([3.14159,2.71828], tf.float32)
print(cool_numbers)

<tf.Variable 'Variable_6:0' shape=(2,) dtype=float32_ref>


In [10]:
first_prims = tf.Variable([2, 3, 5, 7, 11], tf.int32)
print(first_prims)

<tf.Variable 'Variable_7:0' shape=(5,) dtype=int32_ref>


In [13]:
its_very_comlicated = tf.Variable([(12.3, -4.85), (7.5, -6.23)], tf.complex64)
print(its_very_comlicated)
# print(its_very_comlicated.initializer.run())

<tf.Variable 'Variable_10:0' shape=(2, 2) dtype=float32_ref>


## Highter ranks

In [5]:
mymat = tf.Variable(initial_value=[[7],[11]], dtype=tf.int16)
print(mymat)
print(mymat.initializer.run())
print(mymat.eval())

<tf.Variable 'Variable_3:0' shape=(2, 1) dtype=int16_ref>
None
[[ 7]
 [11]]


In [7]:
myxor = tf.Variable(initial_value=[[False, True], [True,True]], dtype=tf.bool)
print(myxor)

<tf.Variable 'Variable_5:0' shape=(2, 2) dtype=bool_ref>


In [17]:
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
print(linear_squares)

<tf.Variable 'Variable_13:0' shape=(4, 1) dtype=int32_ref>


In [10]:
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
print(squarish_squares)
print(squarish_squares.initializer.run())
print(squarish_squares.eval())

<tf.Variable 'Variable_8:0' shape=(2, 2) dtype=int32_ref>
None
[[ 4  9]
 [16 25]]


In [19]:
rank_of_squares = tf.rank(squarish_squares)
print(rank_of_squares)

Tensor("Rank:0", shape=(), dtype=int32)


In [21]:
my_image = tf.zeros([10, 299, 299, 3])
print(my_image)

Tensor("zeros_1:0", shape=(10, 299, 299, 3), dtype=float32)


## Getting a tf.Tensor object's rank

In [25]:
my3d = tf.zeros([10, 299, 3])
r = tf.rank(my3d)
# After the graph runs, r will hold the value 3.

## Referring to tf.Tensor slices
For a rank 0 tensor (a scalar), no indices are necessary, since it is already a single number.

In [29]:
# For a rank 1 tensor (a vector), passing a single index allows you to access a number:
my_vector = tf.Variable([1, 2, 4, 5], dtype=tf.int32)
my_scalar = my_vector[2]

## Changing the shape of a tf.Tensor

In [13]:
rank_three_tensor = tf.ones([3, 4, 5])
print(rank_three_tensor)
print(rank_three_tensor.eval())

Tensor("ones_2:0", shape=(3, 4, 5), dtype=float32)
[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]]


In [14]:
matrix = tf.reshape(rank_three_tensor, [6, 10])
print(matrix.eval())

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [17]:
matrixB = tf.reshape(matrix, [3, -1])
print(matrixB.eval())

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]]


In [18]:
matrixAlt = tf.reshape(matrixB, [4, 3, -1])
print(matrixAlt.eval())

[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]]


In [20]:
# Error
# yet_another = tf.reshape(matrixAlt, [13, 2, -1])

## data type

In [35]:
int_tensor = tf.constant([1, 2, 3])
float_tensor = tf.cast(int_tensor, dtype=tf.float32)
print(int_tensor)
print(float_tensor)

Tensor("Const_12:0", shape=(3,), dtype=int32)
Tensor("Cast_5:0", shape=(3,), dtype=float32)


## Evaluating Tensors

In [32]:
constant = tf.constant([1,2,3])
tensor = constant * constant
print(tensor.eval())
print(type(tensor.eval()))
tensor.eval()

[1 4 9]
<class 'numpy.ndarray'>


array([1, 4, 9], dtype=int32)

In [39]:
p = tf.placeholder(tf.float32)
t = p + 1.0
t.eval(feed_dict={p: 2.0})

3.0

In [42]:
pv = tf.Variable(initial_value=1.0, dtype=tf.float32)
tv = pv + 1.0
tv.eval(feed_dict={pv: 2.0})

3.0

Note that:
tf.train.start_queue_runners

Note that it is possible to feed any tf.Tensor, not just placeholders.

Other model constructs might make evaluating a tf.Tensor complicated. TensorFlow can't directly evaluate tf.Tensors defined inside functions or inside control flow constructs. If a tf.Tensor depends on a value from a queue, evaluating the tf.Tensor will only work once something has been enqueued; otherwise, evaluating it will hang. When working with queues, remember to call tf.train.start_queue_runners before evaluating any tf.Tensors

## Printing Tensor

In [46]:
t = tf.Variable(initial_value=1.0, dtype=tf.float32)
tf.Print(t, [t])  # This does nothing
t = tf.Print(t, [t])  # Here we are using the value returned by tf.Print
result = t + 1  # Now when result is evaluated the value of `t` will be printed.
print(t)
print(result)

Tensor("Print_5:0", shape=(), dtype=float32)
Tensor("add_6:0", shape=(), dtype=float32)
